services:
    php:
        image: php:8.3-apache
        container_name: nouvelleTechno_MVC-demo
        ports:
            - "8007:80" # on définit le port pour accéder à l'application (localhost:8007) faire correspondre avec le PHPMyAdmin
        volumes:
            - :/var/www/html # on monte le dossier courant dans le dossier /var/www/html du container
        build:
            context: .
            dockerfile: Dockerfile # correpond au nom du fichier
    db:
        image: mysql:8.0
        container_name: nouvelleTechno-demo-MVC # identifier le nom du container sur docker
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: nouvelleTechno_MVC
            MYSQL_USER: test
            MYSQL_PASSWORD: test
        ports:
            - "3311:3306"
    phpma:
        image: phpmyadmin/phpmyadmin
        container_name: nouvelleTechno_mvcPHP_phpmyadmin
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: db
            PMA_USER: root
            PMA_PASSWORD: root
            UPLOAD_LIMIT: 20M
        ports:
            - "8087:80" # on définit le port pour accéder à phpmyadmin (localhost:8087) interface graphique pour visualiser la table
